esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton
    version: ${version}
  min_version: 2025.7.0
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s
    - lambda: |-
        // Set version once at boot
        id(printfarmbutton_version).publish_state("${version}");
        ESP_LOGI("version", "Set installed version to: ${version}");
    - if:
        condition:
          lambda: 'return id(cloud_connection).state == "Printago";'
        then:
        - script.execute: check_printago_status

packages:
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  cloud: !include conf.d/cloud.yaml
  cloud_printago: !include conf.d/cloud_printago.yaml
  mqtt: !include conf.d/mqtt.yaml
  mqtt_printago: !include conf.d/mqtt_printago.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  update: !include conf.d/update.yaml
  version: !include conf.d/version.yaml
logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE

ota:
- platform: esphome
- platform: http_request
- platform: web_server

http_request:
  verify_ssl: false

improv_serial:
  next_url: http://{{device_name}}.local

api:
  reboot_timeout: 0s

external_components:
- source:
    type: git
    url: https://github.com/spuder/esphome
    ref: template_select_options
  components: [ template ]
  refresh: 0s
