packages:
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  mqtt: !include conf.d/mqtt.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  printago: !include conf.d/printago.yaml
  update: !include conf.d/update.yaml
  version: !include conf.d/version.yaml
logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE

ota:
- platform: esphome
- platform: http_request

http_request:
  verify_ssl: false

improv_serial:
  next_url: http://{{device_name}}.local

api:
  reboot_timeout: 0s
