esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.PrintFarmButton
    version: ${version}
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s

packages:
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  cloud: !include conf.d/cloud.yaml
  cloud_printago: !include conf.d/cloud_printago.yaml
  cloud_bambu: !include conf.d/cloud_bambu.yaml
  mqtt: !include conf.d/mqtt.yaml
  mqtt_bambu: !include conf.d/mqtt_bambu.yaml
  mqtt_printago: !include conf.d/mqtt_printago.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  update: !include conf.d/update.yaml
  version: !include conf.d/version.yaml
  scripts: !include conf.d/scripts.yaml
logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE

ota:
- platform: esphome
- platform: http_request

http_request:
  verify_ssl: false

improv_serial:
  next_url: http://{{device_name}}.local

api:
  reboot_timeout: 0s
