esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s

packages:
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  mqtt: !include conf.d/mqtt.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  printago: !include conf.d/printago.yaml

logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE

ota:
- platform: esphome
- platform: http_request

http_request:
  verify_ssl: false

esp32_improv:
  authorizer: none

improv_serial:
  next_url: http://{{device_name}}.local
  # substitutions:
  #   board_type: esp32dev
  #   rgb_led_pin: '4'

api:
  reboot_timeout: 0s
