esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton
    version: ${version}
  min_version: 2025.7.0b1 #https://github.com/esphome/esphome/pull/5786
  on_boot:
    then:
      # - text_sensor.template.publish:
      #     id: bambu_status_text
      #     state: "UNKNOWN"
      # - delay: 2s # Give time for components to initialize
      # - light.turn_on:
      #     id: printfarmbutton_rgb
      #     effect: "Rainbow"
      #     brightness: 90%
      # - delay: 3s

packages:
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  cloud: !include conf.d/cloud.yaml
  cloud_printago: !include conf.d/cloud_printago.yaml
  cloud_bambu: !include conf.d/cloud_bambu.yaml
  mqtt: !include conf.d/mqtt.yaml
  mqtt_bambu: !include conf.d/mqtt_bambu.yaml
  mqtt_printago: !include conf.d/mqtt_printago.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  update: !include conf.d/update.yaml
  version: !include conf.d/version.yaml
  scripts: !include conf.d/scripts.yaml
  #debug: !include conf.d/debug.yaml

logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE
  #   http_request: VERBOSE

ota:
- platform: esphome
- platform: http_request

http_request:
  verify_ssl: false

improv_serial:
  next_url: http://{{device_name}}.local

api:
  reboot_timeout: 0s

# TODO: Remove once crashing is fixed
# https://discord.com/channels/429907082951524364/1390941483150082161/1391308828414578688
# https://github.com/esphome/esphome/pull/5786
# external_components:
# - source:
#     type: git
#     url: https://github.com/spuder/esphome
#     # ref: 2025.6.3/mqtt-chunking
#     ref: 2025.7.0b1/mqtt-chunking
#   components: [ mqtt ]
#   refresh: 0s
