# Central ESPHome config for PrintFarmButton
esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s

substitutions:
  board_type: !env_var BOARD_TYPE "esp32-s3"

packages:
  board_esp32_s3: !include
    file: ./boards/esp32-s3.yaml
    vars:
      board_active: !lambda 'return "${board_type}" == "esp32-s3";'

  board_esp32_c3: !include
    file: ./boards/esp32-c3.yaml
    vars:
      board_active: !lambda 'return "${board_type}" == "esp32-c3";'
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  mqtt: !include conf.d/mqtt.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  printago: !include conf.d/printago.yaml

logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE

ota:
  platform: http_request

esp32_improv:
  authorizer: none

improv_serial:
  next_url: http://{{device_name}}.local
  # substitutions:
  #   board_type: esp32dev
  #   rgb_led_pin: '4'

api:
  reboot_timeout: 0s
