# Central ESPHome config for PrintFarmButton
esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s

esp32:
  board: esp32-s3-devkitc-1
  # framework:
  # type: esp-idf

substitutions:
  board_type: esp32-s3 # default, can be overridden via CLI or dashboard

packages:
  board: !include boards/${board_type}.yaml
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  mqtt: !include conf.d/mqtt.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml
  printago: !include conf.d/printago.yaml

logger:
  # level: VERBOSE
  # logs:
  #   mqtt.component: VERBOSE
  #   mqtt.client: VERBOSE
  #   mqtt: VERBOSE

ota:
  platform: http_request

esp32_improv:
  authorizer: none

improv_serial:
  next_url: http://{{device_name}}.local
  # substitutions:
  #   board_type: esp32dev
  #   rgb_led_pin: '4'

api:
  reboot_timeout: 0s
