# Central ESPHome config for OpenQueue
esphome:
  name: openqueue
  friendly_name: OpenQueue
  # name_add_mac_suffix: true
  # platformio_options:
  #   board: ${board_type}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    # version: latest
    # advanced:
    #   ignore_efuse_custom_mac: true

packages:
  #hardware: !include config.d/hardware.yaml
  led: !include conf.d/led.yaml
  web_server: !include conf.d/web_server.yaml
  mqtt: !include conf.d/mqtt.yaml
  button: !include conf.d/button.yaml
  wifi: !include conf.d/wifi.yaml

logger: # api: #can not have mqtt and api at the same time

ota:
  platform: esphome

esp32_improv:
  authorizer: none

# improv_serial:

# substitutions:
#   board_type: esp32dev
#   rgb_led_pin: '4'
#   # mac_suffix: 'XXXX'
