# Central ESPHome config for OpenQueue
esphome:
  name: openqueue
  friendly_name: OpenQueue
  # name_add_mac_suffix: true
  # platformio_options:
  #   board: ${board_type}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    # version: latest
    advanced:
      ignore_efuse_custom_mac: true

packages:
  #hardware: !include config.d/hardware.yaml
  led: !include conf.d/led.yaml
  webserver: !include conf.d/webserver.yaml
  mqtt: !include conf.d/mqtt.yaml
  button: !include conf.d/button.yaml

# logger:
api:
ota:
  platform: esphome
wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  ap:
    # ssid: "OpenQueue-${mac_suffix}"
    ssid: "OpenQueue"
    # password: "openqueue123"
  on_connect:
    then:
    - logger.log: "WiFi Connected!"
  on_disconnect:
    then:
    - logger.log: "WiFi Disconnected! Starting fallback hotspot."
captive_portal:

esp32_improv:
  authorizer: none

# improv_serial:

# substitutions:
#   board_type: esp32dev
#   rgb_led_pin: '4'
#   # mac_suffix: 'XXXX'
