substitutions:
  led_gpio: "12"
  button_gpio: "8"
  manifest_file: "manifest-supermini.json"

# https://www.espboards.dev/esp32/esp32-s3-super-mini/
esp32:
  board: esp32-s3-devkitc-1

packages:
  common: !include common.yaml
