substitutions:
  led_gpio: "1"
  button_gpio: "0"
  manifest_file: "manifest-zero.json"

# https://www.espboards.dev/esp32/esp32-c3-zero/
esp32:
  board: esp32-c3-devkitm-1

packages:
  common: !include common.yaml
