# WARNING: The c3-zero has different GPIOs for button and LED than the c3-supermini.
# It requires manually compiling as esphome web installer doesn't provide a way to select the board.

substitutions:
  led_gpio: "0"
  button_gpio: "1"
  manifest_file: "manifest-zero.json"

# https://www.espboards.dev/esp32/esp32-c3-zero/
esp32:
  board: esp32-c3-devkitm-1

packages:
  common: !include common.yaml

esphome:
  name: pfb-c3-zero
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton
    version: ${version}
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s
