substitutions:
  button_gpio: "1"
  led_gpio: "2"
  manifest_file: "manifest-zero.json"

# https://www.espboards.dev/esp32/esp32-s3-zero/
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
packages:
  common: !include common.yaml
