# WARNING: The c3-zero has different GPIOs for button and LED than the c3-supermini.
# It requires manually compiling as esphome web installer doesn't provide a way to select the board.

substitutions:
  led_gpio: "0"
  button_gpio: "1"
  firmware_name: "esp32c3-zero"

# https://www.espboards.dev/esp32/esp32-c3-zero/
esp32:
  board: esp32-c3-devkitm-1

packages:
  common: !include common.yaml
