substitutions:
  led_gpio: "12"
  button_gpio: "8"
  firmware_name: "esp32s3-supermini"

# https://www.espboards.dev/esp32/esp32-s3-super-mini/
esp32:
  board: esp32-s3-devkitc-1

packages:
  common: !include common.yaml

esphome:
  name: spuder.printfarmbutton-s3-supermini
