substitutions:
  led_gpio: "12"
  button_gpio: "8"

# https://www.espboards.dev/esp32/esp32-s3-super-mini/
esp32:
  board: esp32-s3-devkitc-1

packages:
  common: !include common.yaml

esphome:
  name: pfb-s3-mini
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton-mini
    version: ${version}
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s
