substitutions:
  led_gpio: "1"
  button_gpio: "2"
  manifest_file: "manifest-zero.json"

# https://www.espboards.dev/esp32/esp32-s3-zero/
esp32:
  board: esp32-s3-devkitc-1

packages:
  common: !include common.yaml

esphome:
  name: pfb-s3-zero
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton
    version: ${version}
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s
