substitutions:
  led_gpio: "1"
  button_gpio: "2"
  firmware_name: "esp32s3-zero"

# https://www.espboards.dev/esp32/esp32-s3-zero/
esp32:
  board: esp32-s3-devkitc-1

packages:
  common: !include common.yaml

esphome:
  name: printfarmbutton
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton-s3-zero
    version: ${version}
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s
