substitutions:
  led_gpio: "3"
  button_gpio: "0"
  firmware_name: "esp32c3-supermini"

# https://www.espboards.dev/esp32/esp32-c3-super-mini/
esp32:
  board: esp32-c3-devkitm-1

packages:
  common: !include common.yaml

esphome:
  friendly_name: PrintFarmButton
  name_add_mac_suffix: true
  project:
    name: spuder.printfarmbutton-c3-supermini
    version: ${version}
  on_boot:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        effect: Rainbow
    - delay: 3s
