substitutions:
  button_gpio: "13"
  led_gpio: "12"
  manifest_file: "manifest-supermini.json"

# https://www.espboards.dev/esp32/esp32-s3-super-mini/
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
packages:
  common: !include common.yaml
  button: !include conf.d/button.yaml
