# Button config for OpenQueue
http_request:
  id: http_request_data
  verify_ssl: false

# button:
# - platform: template
#   name: "Confirm Printer Ready"
#   id: confirm_ready_button
#   on_press:
#   # - lambda: |-
#   #     id(check_printago_status).execute();

binary_sensor:
- platform: gpio
  name: "Physical Confirm Printer Ready"
  id: confirm_ready_gpio
  pin:
    number: 2
    mode: INPUT_PULLUP
    inverted: true
    # on_press:
    # - lambda: |-
    #     id(check_printago_status).execute();
