binary_sensor:
- platform: gpio
  name: "Internal Button"
  id: internal_button
  internal: true
  pin:
    number: ${button_internal}
    mode: INPUT_PULLUP
    inverted: true
  filters:
  - delayed_on: 100ms
  - delayed_off: 100ms
  on_press:
    then:
    - logger.log: "Internal button pressed"
    - script.execute: mark_printer_ready
