# Button config for OpenQueue
http_request:
  id: http_request_data
  verify_ssl: false

binary_sensor:
- platform: gpio
  name: "Physical Confirm Printer Ready"
  id: confirm_ready_gpio
  pin:
    number: 2
    mode: INPUT_PULLUP
    inverted: true
  filters:
  - delayed_on: 100ms
  - delayed_off: 100ms
  on_press:
    then:
    - script.execute: mark_printer_ready
