# Button config for PrintFarmButton

binary_sensor:
- platform: gpio
  name: "Physical Confirm Printer Ready"
  id: confirm_ready_gpio
  internal: true
  pin:
    number: ${button_gpio}
    mode: INPUT_DOWN
    inverted: true
  filters:
  - delayed_on: 100ms
  - delayed_off: 100ms
  on_press:
    then:
    - script.execute: mark_printer_ready

# update:
# - platform: http_request
#   name: "Update from GitHub (ESP32-S3)"
#   id: github_ota_update_s3
#   url: "https://raw.githubusercontent.com/spuder/PrintFarmButton/main/firmware/build/firmware-esp32s3.bin"
#   method: GET
#   headers:
#     User-Agent: esphome-ota
# - platform: http_request
#   name: "Update from GitHub (ESP32-C3)"
#   id: github_ota_update_c3
#   url: "https://raw.githubusercontent.com/spuder/PrintFarmButton/main/firmware/build/firmware-esp32c3.bin"
#   method: GET
#   headers:
#     User-Agent: esphome-ota
