# Valid states are
# - "UNKNOWN"
# - "IDLE"
# - "PREPARING"
# - "PRINTING"
# - "COMPLETED"
# - "ERROR"

text_sensor:
- platform: template
  name: "Bambu Status"
  id: bambu_status_text
  icon: "mdi:printer-3d"
  internal: false
  web_server:
    sorting_group_id: bambu
    sorting_weight: 1
  on_value:
    then:
    # Log the status change for debugging
    - lambda: |-
        ESP_LOGI("main", "Bambu status changed to: %s", id(bambu_status_text).state.c_str());
    # - script.execute: update_led_color
  state_topic:
