binary_sensor:
- platform: template
  name: "MQTT Connection"
  id: mqtt_connected
  device_class: connectivity
  web_server:
    sorting_group_id: printago
    sorting_weight: 1
  icon: "mdi:cloud-check-variant-outline"
  lambda: |-
    return id(mqtt_client_id)->is_connected();

text:
- platform: template
  name: "MQTT Endpoint"
  id: mqtt_endpoint_text
  mode: text
  restore_value: true
  optimistic: true
  state_topic:
  web_server:
    sorting_group_id: printago
    sorting_weight: 2
  initial_value: "realtime.printago.io"
  icon: "mdi:lan"
  on_value:
    then:
    - lambda: |-
        ESP_LOGI("mqtt", "MQTT Endpoint changed to: %s", x.c_str());
        id(mqtt_client_id).set_broker_address(x.c_str());

- platform: template
  name: "MQTT Port"
  id: mqtt_port_text
  mode: text
  restore_value: true
  optimistic: true
  state_topic:
  web_server:
    sorting_group_id: printago
    sorting_weight: 3
  initial_value: "8883"
  icon: "mdi:lan"
  on_value:
    then:
    - lambda: |-
        ESP_LOGI("mqtt", "MQTT Port changed to: %s", x.c_str());
        id(mqtt_client_id).set_broker_port(atoi(x.c_str()));
