mqtt:
  id: mqtt_client_id
  broker: ""
  client_id: printfarmbutton
  # port: 8883 #Bambu printers use port 8883. Port is set by connect_mqtt script.
  username: ""
  password: ""
  discover_ip: false
  discovery: false
  discovery_retain: false
  discovery_prefix:
  use_abbreviations: false
  topic_prefix:
  log_topic:
  skip_cert_cn_check: true
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIDljCCAxygAwIBAgISBdvYM0Jo5FEUii0NgRESYx+4MAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    NjAeFw0yNTA3MDcwOTQ1MzhaFw0yNTEwMDUwOTQ1MzdaMB8xHTAbBgNVBAMTFHJl
    YWx0aW1lLnByaW50YWdvLmlvMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEopTO
    bwuVtaNt+xa5ohYRSRheNPtUVgq+YREbWY5u7pSMK4nN36izOstlZ919CLO6lKdq
    rFrXexqFhnAJR4CbTKOCAiMwggIfMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUVGoR
    QOhOfRFVLT/UN6VcCfZu5IwwHwYDVR0jBBgwFoAUkydGmAOpUWiOmNbEQkjbI79Y
    lNIwMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZodHRwOi8vZTYuaS5sZW5j
    ci5vcmcvMB8GA1UdEQQYMBaCFHJlYWx0aW1lLnByaW50YWdvLmlvMBMGA1UdIAQM
    MAowCAYGZ4EMAQIBMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly9lNi5jLmxlbmNy
    Lm9yZy81Ny5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgAN4fIwK9MNwUBi
    EgnqVS78R3R8sdfpMO8OQh60fk6qNAAAAZfkfG1vAAAEAwBHMEUCIQDamGjSxZas
    gQ9MsYMoJ8JUH5dL/tabj0yxwt+RiLzCAAIgeh1Qj+Gb790Hz55H4vBpMqaiLYJj
    oIzQ44gNVjht9coAdwDM+w9qhXEJZf6Vm1PO6bJ8IumFXA2XjbapflTA/kwNsAAA
    AZfkfG2LAAAEAwBIMEYCIQCeHnebLiDXo1RC5QgaXthQ28guh10/J7MFR+DM+nup
    kwIhAL2RWz8HIVeLBfNNWH/LBjdIRUK/nq/Qv8b+vfGeHFkZMAoGCCqGSM49BAMD
    A2gAMGUCMD7iHfRT8AQHqiflgup6LSJu58HqMI1AlL6DVSdK64nS7ncQ7Sur9xhG
    +BV5HD3HbwIxAJiDzzm8R48Kc+s/jT1hYI7Ztwd0G6irBk4aEAaSMYVoSqSrcgci
    b6ax7PRRV+M4Lw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVzCCAj+gAwIBAgIRALBXPpFzlydw27SHyzpFKzgwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCRTYwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAATZ8Z5G
    h/ghcWCoJuuj+rnq2h25EqfUJtlRFLFhfHWWvyILOR/VvtEKRqotPEoJhC6+QJVV
    6RlAN2Z17TJOdwRJ+HB7wxjnzvdxEP6sdNgA1O1tHHMWMxCcOrLqbGL0vbijgfgw
    gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
    ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSTJ0aYA6lRaI6Y1sRCSNsj
    v1iU0jAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
    AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
    BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
    Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAfYt7SiA1sgWGCIpunk46r4AExIRc
    MxkKgUhNlrrv1B21hOaXN/5miE+LOTbrcmU/M9yvC6MVY730GNFoL8IhJ8j8vrOL
    pMY22OP6baS1k9YMrtDTlwJHoGby04ThTUeBDksS9RiuHvicZqBedQdIF65pZuhp
    eDcGBcLiYasQr/EO5gxxtLyTmgsHSOVSBcFOn9lgv7LECPq9i7mfH3mpxgrRKSxH
    pOoZ0KXMcB+hHuvlklHntvcI0mMMQ0mhYj6qtMFStkF1RpCG3IPdIwpVCQqu8GV7
    s8ubknRzs+3C/Bm19RFOoiPpDkwvyNfvmQ14XkyqqKK5oZ8zhD32kFRQkxa8uZSu
    h4aTImFxknu39waBxIRXE4jKxlAmQc4QjFZoq1KmQqQg0J/1JF8RlFvJas1VcjLv
    YlvUB2t6npO6oQjB3l+PNf0DpQH7iUx3Wz5AjQCi6L25FjyE06q6BZ/QlmtYdl/8
    ZYao4SRqPEs/6cAiF+Qf5zg2UkaWtDphl1LKMuTNLotvsX99HP69V2faNyegodQ0
    LyTApr/vT01YPE46vNsDLgK+4cL6TrzC/a4WcmF5SRJ938zrv/duJHLXQIku5v0+
    EwOy59Hdm0PT/Er/84dDV0CSjdR/2XuZM3kpysSKLgD1cKiDA+IRguODCxfO9cyY
    Ig46v9mFmBvyH04=
    -----END CERTIFICATE-----
  clean_session: true
  enable_on_boot: false
  birth_message:
    topic:
    payload:
  will_message:
    topic:
    payload:
  on_disconnect:
    then:
    - logger.log: "MQTT Disconnected!"
    - if:
        condition:
          lambda: 'return id(cloud_connection).state == "Bambu";'
        then:
        - lambda: 'id(bambu_status_text).publish_state("UNKNOWN");'
    - if:
        condition:
          lambda: 'return id(cloud_connection).state == "Printago";'
        then:
        - script.execute: clear_printago_status
    - script.execute: update_led_color
