mqtt:
  id: mqtt_client_id
  # broker: ""
  broker: ""
  client_id: ""
  port: 1883
  username: ""
  password: ""
  discover_ip: false
  discovery: false
  discovery_retain: false
  discovery_prefix:
  use_abbreviations: false
  topic_prefix:
  log_topic: # skip_cert_cn_check: true

  clean_session: true
  enable_on_boot: false # Don't auto-connect, we'll connect manually when ready
  birth_message:
    topic:
    payload:
  will_message:
    topic:
    payload:
      # on_connect:
      # - logger.log:
      #     format: "MQTT Connected."
  on_disconnect:
    then:
    - light.turn_on:
        id: printfarmbutton_rgb
        red: 1.0
        green: 1.0
        blue: 1.0
        effect: None

binary_sensor:
- platform: template
  name: "MQTT Connection"
  id: mqtt_connected
  device_class: connectivity
  web_server:
    sorting_group_id: printago
    sorting_weight: 7
  icon: "mdi:cloud-check-variant-outline"
  lambda: |-
    return id(mqtt_client_id)->is_connected();

text:
- platform: template
  name: "MQTT Endpoint"
  id: mqtt_endpoint_text
  mode: text
  restore_value: true
  optimistic: true
  state_topic:
  web_server:
    sorting_group_id: printago
    sorting_weight: 6
  initial_value: "mqtt.example.com"
  icon: "mdi:lan"
  on_value:
    then:
    - lambda: |-
        ESP_LOGI("mqtt", "MQTT Endpoint changed to: %s", x.c_str());
        id(mqtt_client_id).set_broker_address(x.c_str());
