mqtt:
  id: mqtt_client_id
  # broker: ""
  broker: "192.168.81.154"
  client_id: ""
  port: 1883
  username: ""
  password: ""
  discover_ip: false
  discovery: false
  discovery_retain: false
  discovery_prefix:
  use_abbreviations: false
  topic_prefix:
  log_topic: # skip_cert_cn_check: true

  clean_session: true
  enable_on_boot: false # Don't auto-connect, we'll connect manually when ready
  birth_message:
    topic:
    payload:
  will_message:
    topic:
    payload:
      # on_connect:
      # - logger.log:
      #     format: "MQTT Connected."
      # - lambda: |-
      #     id(check_printago_status).execute(id(printer_id).state, id(api_key_text).state, id(username_text).state);
binary_sensor:
- platform: template
  name: "MQTT Connection"
  id: mqtt_connected
  device_class: connectivity
  lambda: |-
    return id(mqtt_client_id)->is_connected();

text:
- platform: template
  name: "MQTT Endpoint"
  id: mqtt_endpoint_text
  mode: text
  restore_value: true
  optimistic: true
  state_topic:
  web_server:
    sorting_group_id: printago

- platform: template
  name: "Last MQTT Message"
  id: last_mqtt_message
  mode: text
  restore_value: false
  optimistic: true
  state_topic:
  web_server:
    sorting_group_id: diagnostic
