text:
- platform: template
  name: Printer Serial Number
  id: bambu_serial_number
  state_topic:
  optimistic: true
  mode: text
  restore_value: true
  icon: mdi:barcode
  web_server:
    sorting_group_id: bambu
    sorting_weight: 3
  on_value:
    then:
    - script.execute: connect_mqtt

- platform: template
  name: Printer Lan Access Code
  id: bambu_lan_access_code
  state_topic:
  optimistic: true
  mode: password
  restore_value: true
  icon: mdi:lock
  web_server:
    sorting_group_id: bambu
    sorting_weight: 4
  on_value:
    then:
    - script.execute: connect_mqtt

- platform: template
  name: Printer IP Address
  id: bambu_ip_address
  state_topic:
  optimistic: true
  mode: text
  restore_value: true
  icon: mdi:ip
  web_server:
    sorting_group_id: bambu
    sorting_weight: 2
  on_value:
    then:
    - script.execute: connect_mqtt

- platform: template
  name: "Bambu MQTT Port"
  id: mqtt_port_bambu
  mode: text
  optimistic: true
  restore_value: true
  initial_value: "8883"
  web_server:
    sorting_group_id: bambu
    sorting_weight: 5
  icon: "mdi:numeric"
  on_value:
    then:
    - script.execute: connect_mqtt
