name: Build ESPHome Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1  # Force sequential builds to avoid directory conflicts
      matrix:
        include:
          - target: esp32s3-zero
            yaml_file: esp32s3-zero.yaml
          - target: esp32s3-supermini
            yaml_file: esp32s3-supermini.yaml
          - target: esp32c3-zero
            yaml_file: esp32c3-zero.yaml
          - target: esp32c3-supermini
            yaml_file: esp32c3-supermini.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create empty secrets file
        run: |
          touch firmware/esphome/secrets.yaml || true
      
      - name: Setup yq
        uses: vegardit/gha-setup-yq@v1

      - name: Set git sha
        run: |
          SUMMARY=$(git log -1 --pretty=%B)
          SUMMARY="${SUMMARY//'%'/'%25'}"
          SUMMARY="${SUMMARY//$'\n'/'%0A'}"
          SUMMARY="${SUMMARY//$'\r'/'%0D'}"
          echo "RELEASE_SUMMARY=$SUMMARY" >> $GITHUB_ENV

      - name: Modify version.yaml
        run: |
          yq -i '.substitutions.version = "${{ github.ref_name }}"' firmware/esphome/conf.d/version.yaml
          cat firmware/esphome/conf.d/version.yaml

      - name: Build firmware
        uses: esphome/build-action@v6
        with:
          yaml-file: firmware/esphome/${{ matrix.yaml_file }}
          complete-manifest: false

      - name: List build output
        run: |
          ls -la
          echo "Looking for build directories..."
          for dir in printfarmbutton*; do
            if [ -d "$dir" ]; then
              echo "Found build directory: $dir"
              ls -la "$dir/" || true
            fi
          done

      - name: Rename build directory to avoid conflicts
        run: |
          # Find the actual build directory
          BUILD_DIR=""
          for dir in printfarmbutton*; do
            if [ -d "$dir" ]; then
              BUILD_DIR="$dir"
              break
            fi
          done
          
          if [ -z "$BUILD_DIR" ]; then
            echo "Error: No build directory found"
            exit 1
          fi
          
          # Rename to target-specific directory
          NEW_DIR="${{ matrix.target }}-build"
          echo "Renaming $BUILD_DIR to $NEW_DIR"
          mv "$BUILD_DIR" "$NEW_DIR"
          ls -la "$NEW_DIR"

      - name: Generate md5 checksum
        run: |
          BUILD_DIR="${{ matrix.target }}-build"
          echo "Using build directory: $BUILD_DIR"
          ls -la "$BUILD_DIR"
          for file in "$BUILD_DIR"/*.bin; do
            if [ -f "$file" ]; then
              md5sum "$file" | awk '{print $1}' > "${file}.md5"
              md5_length=$(wc -c < "${file}.md5")
              if [ "$md5_length" -ne 33 ]; then
                echo "MD5 generation failed for $file (length: $md5_length)"
                exit 1
              fi
            fi
          done
          ls -la "$BUILD_DIR"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.target }}-build/**/*
          retention-days: 5
          if-no-files-found: error

  combine-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: List artifacts
        run: |
          echo "Downloaded artifacts structure:"
          ls -la downloaded-artifacts/
          echo ""
          echo "Contents of each artifact:"
          for dir in downloaded-artifacts/*/; do
            if [ -d "$dir" ]; then
              echo "=== Contents of $dir ==="
              ls -la "$dir"
              echo ""
            fi
          done

      - name: Prepare output directory
        run: |
          mkdir -p firmware/output
          for target in esp32s3-supermini esp32s3-zero esp32c3-supermini esp32c3-zero; do
            if [ -d "downloaded-artifacts/$target" ]; then
              # Determine new filename pattern: printfarmbutton-<type>-<family>
              board_type=""
              chip_family=""
              if [[ "$target" == *"supermini"* ]]; then
                board_type="supermini"
              elif [[ "$target" == *"zero"* ]]; then
                board_type="zero"
              fi
              
              if [[ "$target" == *"s3"* ]]; then
                chip_family="esp32s3"
              elif [[ "$target" == *"c3"* ]]; then
                chip_family="esp32c3"
              fi
              
              # Rename files to include board type and chip family
              for bin_file in downloaded-artifacts/$target/*.bin; do
                if [ -f "$bin_file" ]; then
                  filename=$(basename "$bin_file")
                  # Replace printfarmbutton with printfarmbutton-<type>-<family>
                  new_filename=$(echo "$filename" | sed "s/printfarmbutton/printfarmbutton-$board_type-$chip_family/")
                  cp "$bin_file" "firmware/output/$new_filename"
                fi
              done
              for md5_file in downloaded-artifacts/$target/*.md5; do
                if [ -f "$md5_file" ]; then
                  filename=$(basename "$md5_file")
                  # Replace printfarmbutton with printfarmbutton-<type>-<family>
                  new_filename=$(echo "$filename" | sed "s/printfarmbutton/printfarmbutton-$board_type-$chip_family/")
                  cp "$md5_file" "firmware/output/$new_filename"
                fi
              done
            fi
          done

      - name: Get version from git tag or branch
        id: get_version
        run: |
          # Prefer tags that do NOT start with 'v' if both exist on the same commit
          VERSION=$(git tag --points-at HEAD | grep -E '^[0-9]+\.[0-9]+\.[0-9]+' | head -n1)
          if [ -z "$VERSION" ]; then
            VERSION=${GITHUB_REF_NAME}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create manifest files
        run: |
          # Create separate manifests for OTA updates
          jq -n --arg version "$VERSION" '{
            name: "PrintFarmButton SuperMini",
            version: $version,
            builds: [],
            new_install_prompt_erase: true
          }' > firmware/output/manifest-supermini.json

          jq -n --arg version "$VERSION" '{
            name: "PrintFarmButton Zero",
            version: $version,
            builds: [],
            new_install_prompt_erase: true
          }' > firmware/output/manifest-zero.json

          echo "Looking for build artifacts..."
          for target in esp32s3-supermini esp32s3-zero esp32c3-supermini esp32c3-zero; do
            echo "Processing build: $target"
            
            # Check if the artifact directory exists
            if [ -d "downloaded-artifacts/$target" ]; then
              echo "Found artifact directory: downloaded-artifacts/$target"
              ls -la "downloaded-artifacts/$target"
              
              # Determine project name, target manifest, and filename pattern
              project_name="spuder.printfarmbutton"
              target_manifest=""
              board_type=""
              chip_family=""
              
              if [[ "$target" == *"supermini"* ]]; then
                target_manifest="firmware/output/manifest-supermini.json"
                board_type="supermini"
              elif [[ "$target" == *"zero"* ]]; then
                target_manifest="firmware/output/manifest-zero.json"
                board_type="zero"
              else
                echo "Error: Cannot determine target manifest for: $target"
                exit 1
              fi
              
              if [[ "$target" == *"s3"* ]]; then
                chip_family="esp32s3"
              elif [[ "$target" == *"c3"* ]]; then
                chip_family="esp32c3"
              fi
              
              # Check if manifest.json exists
              if [ -f "downloaded-artifacts/$target/manifest.json" ]; then
                echo "Found ESPHome-generated manifest.json for $target"
                echo "Manifest contents:"
                cat "downloaded-artifacts/$target/manifest.json"
                
                # Process the manifest and update file paths to use renamed files
                manifest_content=$(cat "downloaded-artifacts/$target/manifest.json")
                
                # Update file paths in the manifest to use renamed files
                updated_manifest=$(echo "$manifest_content" | jq --arg board_type "$board_type" --arg chip_family "$chip_family" --arg project "$project_name" '
                  . + {"project": $project} |
                  if .parts then .parts = [.parts[] | .path = (.path | gsub("printfarmbutton"; "printfarmbutton-" + $board_type + "-" + $chip_family))] else . end |
                  if .ota then .ota.path = (.ota.path | gsub("printfarmbutton"; "printfarmbutton-" + $board_type + "-" + $chip_family)) else . end
                ')
                
                # Add the build entry to the target manifest only
                jq --argjson new_build "$updated_manifest" '.builds += [$new_build]' "$target_manifest" > temp.json && mv temp.json "$target_manifest"
                
                echo "Successfully added $target to manifest using ESPHome manifest"
              else
                echo "No ESPHome manifest found for $target, creating fallback entry..."
                
                # Create fallback manifest entry
                chip_family_name="ESP32"
                if [[ "$target" == *"s3"* ]]; then
                  chip_family_name="ESP32-S3"
                elif [[ "$target" == *"c3"* ]]; then
                  chip_family_name="ESP32-C3"
                fi
                
                # Look for binary files (use renamed files in output directory)
                factory_bin=""
                ota_bin=""
                
                # Check for renamed files in output directory
                if [ -f "firmware/output/printfarmbutton-$board_type-$chip_family.factory.bin" ]; then
                  factory_bin="printfarmbutton-$board_type-$chip_family.factory.bin"
                fi
                
                if [ -f "firmware/output/printfarmbutton-$board_type-$chip_family.ota.bin" ]; then
                  ota_bin="printfarmbutton-$board_type-$chip_family.ota.bin"
                fi
                
                # Create manifest entry
                if [ -n "$factory_bin" ] && [ -n "$ota_bin" ]; then
                  echo "Creating full manifest entry with factory and OTA binaries"
                  manifest_entry=$(jq -n --arg chip "$chip_family_name" --arg project "$project_name" --arg factory_path "$factory_bin" --arg ota_path "$ota_bin" '{
                    "chipFamily": $chip, 
                    "project": $project, 
                    "parts": [{"path": $factory_path, "offset": 0}],
                    "ota": {"path": $ota_path}
                  }')
                elif [ -n "$factory_bin" ]; then
                  echo "Creating manifest entry with factory binary only"
                  manifest_entry=$(jq -n --arg chip "$chip_family_name" --arg project "$project_name" --arg factory_path "$factory_bin" '{
                    "chipFamily": $chip, 
                    "project": $project, 
                    "parts": [{"path": $factory_path, "offset": 0}]
                  }')
                else
                  echo "Error: No binary files found for $target"
                  echo "Available files:"
                  ls -la "downloaded-artifacts/$target/"
                  exit 1
                fi
                
                # Add to target manifest only
                jq --argjson new_build "$manifest_entry" '.builds += [$new_build]' "$target_manifest" > temp.json && mv temp.json "$target_manifest"
                
                echo "Successfully created fallback manifest entry for $target"
              fi
            else
              echo "Error: Artifact directory not found: downloaded-artifacts/$target"
              echo "Available artifacts:"
              ls -la downloaded-artifacts/
              exit 1
            fi
          done

          echo "Final supermini manifest:"
          jq '.' firmware/output/manifest-supermini.json
          echo ""
          echo "Final zero manifest:"
          jq '.' firmware/output/manifest-zero.json

      - name: List files in output directory
        run: |
          echo "Contents of firmware/output:"
          ls -lh firmware/output/

      - name: Commit and push build artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git stash push -m "Stash before switching to main"
          git checkout main
          git pull origin main
          git stash apply || true
          git add firmware/output/
          git add firmware/esphome/conf.d/version.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update firmware build and version.yaml [skip ci]"
            git push origin main
          fi